### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by sachin0606** [gfto/mptsd#11]
Hi , 

how i can use this for DVB-C as in config file you shown for the transponder in NIT.config

**Comment by gfto** [comment]
There are example configs, that show how to configure everything. Please use them.

**Comment by sachin0606** [comment]
thanks will try to use them , in between to itntegrate the xmltv , can you guide me how to do that, as i am .net developer not much know about c projects. give me file names and modules where we need to modify will try to add them.
