### ISSUE TITLE
Update submodules

### ISSUE THREAD

**Issue by lars18th** [gfto/mptsd#12]
Hi,

The current "master" Branch uses quite old versions of submodules (three years ago!).
You can see the used versions:
```
libfuncs @ 0dc8d87
libtsfuncs @ 45e7e99
```

And the command `git submodule update` doesn't update the code of the submodules.
Check it at https://gist.github.com/gitaarik/8735255.

So, I suggest to update the submodules to a recent commit.
And futhermore, add to the README how to update the submodules to last versions with the command `git submodule update --recursive --remote`

Regards.

**Comment by gfto** [comment]
Merged.

**Comment by lars18th** [comment]
Hi @gfto ,

Thank you for the merge! However, still ancient versions in the master branch.
To "update" the submodules links, I recommend to do this simple commit:

- Clone the repository.
- Execute the command `git submodule update --recursive --remote`.
- Commit the change.

This will update the master branch to the most recent versions. At time, the referenced versions are quite old; and the current versions compile and run without problems.

Please... :pray:
