### ISSUE TITLE
LCN branch to master

### ISSUE THREAD

**Issue by lars18th** [gfto/mptsd#14]
Hi,

I see that the "lcn" branch has useable code for supporting LCN descriptors. Plus some other code of an UDP server.

I suggest the idea of extracting the LCN code and merge it with the "main" branch.
You agree?

**Comment by gfto** [comment]
Send MR and I'll merge it.

**Comment by lars18th** [comment]
> Send MR and I'll merge it.

Well, then I need to mirror your branch, delete the code regarding the UDP server, and create a PR.
Now, I see that the original developer is @gmakedonski... committed four years ago (and now removed).

I'll try to spplit the LCN part from the UDP server (that I don't know the objective of this server); an create a PR.

Regards.

**Comment by lars18th** [comment]
This PR #41 implements this.

**Comment by lars18th** [comment]
I close this issue because it's merged.
