### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AMDmi3** [gfto/mptsd#17]
Would be nice to do a new official release of mptsd with the recent changes and newer dependencies (at least libtsfuncts) to simplify packaging.

**Comment by lars18th** [comment]
Hi @AMDmi3 ,

A lot of "new" functionalities and some "fixes" are now merged. After we finish this, I suggest to @gfto to create a new "release" version.

**Comment by gfto** [comment]
I'll wait a few days for the dust to settle after all the code merges today and I'll release a new version then.
