### ISSUE TITLE
epg from xmltv import option

### ISSUE THREAD

**Issue by satcable2005** [gfto/mptsd#4]
hello sir,
first thanx to you for great great software for small network.
my request to you,
can you sopport for xmltv  for epg?
i have xmltv file so can i use in mptsd-lcn?
or can i put xmltv link to epg option?
thnx dear.

**Comment by Saentist** [comment]
+1 for EPG passthrough

**Comment by lars18th** [comment]
Hi @gfto ,

Because this issue is now fixed (in https://github.com/gfto/mptsd/commit/be2845afdcd2e66ea0dc6182d9b031e00f28d18c) , please close it.

**Comment by gfto** [comment]
Closing the issue since it's fixed in https://github.com/gfto/mptsd/commit/be2845afdcd2e66ea0dc6182d9b031e00f28d18c
