### ISSUE TITLE
pls add Bouquet Association Table (BAT)

### ISSUE THREAD

**Issue by satcable2005** [gfto/mptsd#6]
hello sir,
does it possible to add Bouquet Association Table (BAT) with lcn?
i am waiting for your great help.
thnx.

**Comment by lars18th** [comment]
Hi @satcable2005 ,

The LCN support (partially) has been implemented by others in https://github.com/lars18th/mptsd/commit/e38fb3bd29ad2d190ff16ec86e5375d5bf064053

If you still want it, I can prepare a commit with only this part.

**Comment by lars18th** [comment]
Hi @gfto ,

I feel the implementation to support more systems (DVB-T) and tables (BAT) will be desirable. But you can add it the TODO list, and close this old issue. You agree?
