### ISSUE TITLE
SID 550 results in invalid stream

### ISSUE THREAD

**Issue by bogdane** [gfto/mptsd#9]
HI.
Setting SIDs of 550, 551 and 552 for a stream with 3 programs made the stream broken/invalid ("invalid headers" reported by VLC, no image on QAM). I lowered it to 500, 501 and 502 and it was ok.
I assume there is a problem with SIDs higher than 511?

**Comment by ningpeng** [comment]
I meet the simular problem when config big service id ,  and I fix the problem , PLS see it in my fork .

**Comment by bogdane** [comment]
Thanks for the info. I will try it next time I will need higher SIDs.

**Comment by lars18th** [comment]
Time to close this issue?
